wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1648739080
    t:
      1:
      - 1
      - 11
      - 49
      2:
      - 1
      - 11
      - 49
      3:
      - 1
      4: 3.9.1
      5: 0.12.11
      6: 4.16.2
      8:
      - 3
      - 5
